// app/layout.tsx (محدث)
import type { Metadata } from "next";
import { Cairo } from 'next/font/google';
import Footer from "../components/Footer";
import AppSidebar from "@/components/app-sidebar";
import "./globals.css";
import { MediaRecorderProvider } from '@/contexts/MediaRecorderContext';
import "react-datepicker/dist/react-datepicker.css";
import "react-toastify/dist/ReactToastify.css";
const cairo = Cairo({
  subsets: ['latin', 'arabic'],
  weight: ['300', '400', '600', '700'],
  display: 'swap',
  variable: '--font-cairo',
});

export const metadata: Metadata = {
  title: ">منصة الإعتماد العربي",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ar" className={`${cairo.variable} font-sans`}>
       <head>
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap"
        />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Cairo:wght@300;400;600;700&display=swap"
        />
        <title>منصة الإعتماد العربي</title>
      </head>
      <body className="flex flex-col min-h-screen">
        {/* المحتوى الرئيسي */}
        <div className="flex-1">
          <div className="hidden lg:block">
            <AppSidebar variant="header" />
            <main className="pt-16"> <MediaRecorderProvider>
          {children}
        </MediaRecorderProvider></main>
          </div>
          <div className="block lg:hidden flex">
            <main className="flex-1 p-4">{children}</main>
          </div>
        </div>
        
        {/* الفوتر */}
        <Footer />
      </body>
    </html>
  );
}