// app/layout.tsx (محدث)
import type { Metadata } from "next";
import { Cairo } from 'next/font/google';
import Footer from "../components/Footer";
import AppSidebar from "@/components/app-sidebar";
import "./globals.css";

const cairo = Cairo({
  subsets: ['latin', 'arabic'],
  weight: ['300', '400', '600', '700'],
  display: 'swap',
  variable: '--font-cairo',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ar" className={`${cairo.variable} font-sans`}>
      <body className="flex flex-col min-h-screen">
        {/* المحتوى الرئيسي */}
        <div className="flex-1">
          <div className="hidden lg:block">
            <AppSidebar variant="header" />
            <main className="pt-16">{children}</main>
          </div>
          <div className="block lg:hidden flex">
            <AppSidebar variant="sidebar" />
            <main className="flex-1 p-4">{children}</main>
          </div>
        </div>
        
        {/* الفوتر */}
        <Footer />
      </body>
    </html>
  );
}