import type { Metadata } from "next";
import React from "react";
import "./globals.css";
import Footer from "@/components/Footer";
import AppSidebar from "@/components/app-sidebar";
import { Cairo } from 'next/font/google';

const cairo = Cairo({
  subsets: ['latin', 'arabic'],
  weight: ['300', '400', '600', '700'],
  display: 'swap',
  variable: '--font-cairo', // إضافة متغير للاستخدام العام
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en"  className={cairo.className}>
      <body className="flex flex-col min-h-screen {`${cairo.variable} font-sans`}">
        {/* المحتوى الرئيسي */}
        <div className="flex-1">
          {/* للشاشات الكبيرة */}
          <div className="hidden lg:block">
            <AppSidebar variant="header" />
            <main className="pt-16">{children}</main>
          </div>
          {/* للشاشات الصغيرة */}
          <div className="block lg:hidden flex">
            <AppSidebar variant="sidebar" />
            <main className="flex-1 p-4">{children}</main>
          </div>
        </div>
        {/* الفوتر يظهر دائماً في الأسفل */}
        <Footer />
      </body>
    </html>
  );
}
